project:
  type: website

lang: es
date-format: iso

execute:
  freeze: auto

website:
  title: "Botánica, 2025-2"
  description: |
    Sitio web del curso Botánica (2025-2) del programa de Ingeniería Agronómica 
    del TdeA Institución Universitaria. 
  site-url: https://biologia-plantas.github.io/tdea-2025-2/
  repo-url: https://github.com/biologia-plantas/tdea-2025-2/
  favicon: imagenes/bldp.png
  image: imagenes/bldp.png
  # repo-actions: [edit, source, issue]

  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true

  google-analytics:
    tracking-id: "G-S36JWWK7HL"
    anonymize-ip: true

  twitter-card:
    creator: "@alexespinosaco"
    card-style: summary_large_image

  open-graph: true

  sidebar:
    style: docked
    logo: imagenes/bldp.png
    search: true
    pinned: true
    align: center

    tools: 
      - text: "Repositorio"
        icon: github
        href: https://github.com/biologia-plantas/2025-2/
      - text: "Guía de laboratorio"
        icon: book
        href: https://www.tdea.edu.co/images/tdea/galeria/2024/PDF/Gu%C3%ADa%20de%20laboratorios%20de%20Bot%C3%A1nica%20y%20Fisiolog%C3%ADa_.pdf

    contents:
      - section: "Información del curso"
        contents:
          - text: "Inicio"
            href: index.qmd
          - text: "Guía de laboratorio"
            href: https://www.tdea.edu.co/images/tdea/galeria/2024/PDF/Gu%C3%ADa%20de%20laboratorios%20de%20Bot%C3%A1nica%20y%20Fisiolog%C3%ADa_.pdf
          - text: "Enlaces de utilidad"
            href: enlaces.qmd
      - section: "Presentaciones"
        contents:
          - text: "Introducción a la botánica"
            href: presentaciones/introduccion-botanica/
          - text: "Citología"
            href: presentaciones/citologia/
          - text: "Histología"
            href: presentaciones/histologia/
          - text: "Diversidad"
            href: presentaciones/diversidad/
          - text: "Raíz"
            href: presentaciones/raiz/
          - text: "Tallo"
            href: presentaciones/tallo/
          - text: "Hoja"
            href: presentaciones/hoja/
          - text: "Flor"
            href: presentaciones/flor/

  page-footer: 
    left: Álex Espinosa-Correa © 2025. Este sitio web está bajo una licencia [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
    right: Hecho por [\@alexespinosaco](https://alexespinosaco.github.io) con [![](https://www.r-project.org/logo/Rlogo.svg){fig-alt="R" width=21px}](https://www.r-project.org/) y [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)

csl: apa.csl

crossref: 
  fig-title: Fig

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    css: styles.scss
    mainfont: "Atkinson Hyperlegible"
    respect-user-color-scheme: true
